from pyrsistent import v


to_english = {
    "ستيشن": 'Presentation',
  "البروجيكتور": 'Project',
  "والكراتين": 'criteria',
  "والكريكتير": 'criteria',
  "تنتيشن": 'Presentation',
  "برزنتيشن": 'Presentation',
  "من": "Man",
  "بالانسد": "Balanced",
  "اكونت": "Account",
  "سيتيزن": "Citizen",
  "فينقر": "Finger",
  "انشورانس": "Insurance",
  "ويندو": "Window",
  "بوسبيلتي": "Possibility",
  "بان": "Ban",
  "ثانكيو": "Thank you",
  "دونتبيساد": "Don't be sad",
  "ابروتش": "Approach",
  "سورنيس": "Soreness",
  "داركنس": "Darkness",
  "ديفل": "Devil",
  "انفورميشن": "Information",
  "كب": "Cup",
  "بد": "Bed",
  "براون": "Brown",
  "نيوز": "News",
  "كالوري": "Calorie",
  "قواهيد": "Go ahead",
  "إسبيشالي": "especially",
  "شل": "Chill",
  "شيل": "Chill",
  "البروجكت": "project",
  "البروجكتر": "project",
  "كرايتيريا": "criteria",
  "كريتيريا": "criteria", 
  "بروجكت": "project",
  "مان": "man",
  "داش": "Dash",
  "ايرثكويك": "Earthquake",
  "اوبيدينس": "Obedience",
  "ترايون": "try one",
  "ريزالتس": "Results",
  "تايت": "tight",
  "إنجاستس": "injustice",
  "قروب": "Group",
  "كلاسيفاي": "Classify",
  "لونق": "long",
  "رايتر": "Writer",
  "نورمال": "Normal",
  "برايس": "Price",
  "ميموري": "Memory",
  "ايفولوشن": "Evolution",
  "كيرفول": "Be careful",
  "كومبتشان": "Competition",
  "كالندر": "Calendar",
  "شارب": "Sharp",
  "دستانس": "Distance",
  "لُووس": "loose",
  "دونوري": "Don't worry",
  "سورسيز": "Sources",
  "سوليوشنز": "solutions",
  "أبلتيز": "Abilities",
  "فيرنيس": "fairness",
  "نايتمير": "Nightmare",
  "أد": "add",
  "بالكوني": "Balcony",
  "بنانا": "banana",
  "اللو": "allow•",
  "بيوتي": "Beauty",
  "بوك": "book",
  "بايبي": "baby",
  "كيرفلي": "Carefully",
  "ريلايز": "realize",
  "كونفيدنس": "Confidence",
  "سترينج": "Strange",
  "امازون": "Amazon"
}
